noun1 = raw_input("linving thing")
verb1 = raw_input("action")
verb2 = raw_input("verb")
verb3 = raw_input("verb")
noun2 = raw_input("noun")
location = raw_input("location")
noun3 = raw_input("noun")
noun4 = raw_input("noun")
noun5 = raw_input("noun")
verb4 = raw_input("verb")


print("As a(n) " + noun1 + " you would wait")
print("And watch from far away.")
print("But you always knew you'd be the one")
print("that " + verb1 + " while they all play.\n")

print("In youth you'd " + verb2)
print("Awake at night and " + verb3)
print("of all the things that you would change,")
print("But it was just a dream!\n")

print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("From " + noun3 + ".\n")

print("The Time will come")
print("When you'll have to rise")
print("Above the rest and prove yourself,")
print("Your " + noun4 + " never dies.\n")

print("Farewell, I've gone to take my " + noun5 + " above,")
print("But don't " + verb4 + " for me")
print("'cause this will be")
print("the labor of my love.\n")

print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("From " + noun3 + ".\n")

print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("Here we are, don't turn away now,")
print("We are the " + noun2 + " that built this " + location + ".")
print("From " + noun3 + ".")
